[ClassVersion("1.0.0.0"), FriendlyName("xMARSAgentSetup")]
class MSFT_xMARSAgentSetup : OMI_BaseResource
{
    [Key, Description("An enumerated value that describes if the MARS agent is expected to be installed on the machine.\nPresent {default}  \nAbsent   \n"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write, Description("UNC path to the root of the source files for installation.")] String SourcePath;
    [Write, Description("Folder within the source path containing the source files for installation.")] String SourceFolder;
    [Write, EmbeddedInstance("MSFT_Credential"), Description("Credential to be used to perform the installation.")] String SetupCredential;
    [Write, EmbeddedInstance("MSFT_Credential"), Description("Credential to be used to access SourcePath.")] String SourceCredential;
    [Write, Description("Suppress reboot.")] Boolean SuppressReboot;
    [Write, Description("Force reboot.")] Boolean ForceReboot;
    [Write, Description("Address of proxy server to be connected")] String ProxyServerAddress;
    [Write, Description("Port of proxy server to be connected")] String ProxyServerPort;
    [Write, EmbeddedInstance("MSFT_Credential"), Description("Credential to be used to Connect to proxy server.")] String ProxyServerCredential;
    [Write, Description("No Update.")] Boolean UseNoUpdateFlag;
};